### PR TITLE
React component

### PR DESCRIPTION
**Pull request by chem2016**
add react template including npm packages to this branch

### CODE REVIEW

**Comment by chem2016** [comment]
@5t4mp5 @KristyHSC @ami-domadia 

adding npm packages and react minimal template to this branch, waiting for approval.

**Review by ami-domadia — COMMENTED** [review]
Hi @chem2016 can you remove the ^ signs from the package.json file so that each thing is stuck to that version and so that we all get the same version?

**Comment by chem2016** [comment]
@ami-domadia Sure, I just updated it.

**Comment by ami-domadia** [comment]
Thank you!

**Comment by chem2016** [comment]
@ami-domadia Could you approve the pull request?

**Review by 5t4mp5 — APPROVED** [review]

**Review by ami-domadia — APPROVED** [review]

**Review by ami-domadia — APPROVED** [review]

**Review by 5t4mp5 — APPROVED** [review]

**Pull request merged**
