### PR TITLE
Order and other components

### PR DESCRIPTION
**Pull request by chem2016**
Add a order component and updates on checkout form

### CODE REVIEW

**Comment by 5t4mp5** [comment]
Your code works, however I would make the following changes.

1. I would make the card type field a Select input. They have to be entered spelled exactly as is, all lowercase. This will avoid users entering in their card type incorrectly.

2. I would also make cc expiration month a Select input. However you show it on the front end (spelling out the month, or showing a number) the value sent to the DB must be an integer 1-12.

**Comment by chem2016** [comment]
@5t4mp5 This commit address your comments above.

**Comment by chem2016** [comment]
@5t4mp5 @KristyHSC @ami-domadia , I fix the bug and now we can create an order.

**Comment by chem2016** [comment]
@5t4mp5 @KristyHSC @ami-domadia , I created the order table, now we can create an order and get an order

**Review by ghost — APPROVED** [review]

**Pull request merged**
