### PR TITLE
React component

### PR DESCRIPTION
**Pull request by chem2016**
I have added some fake data and cart to the front end

### CODE REVIEW

**Review by ami-domadia — COMMENTED** [review]
Can you remove the conflict with server.js?

**Comment by chem2016** [comment]
@ami-domadia conflict solved, could you approve this case. Thanks!

**Comment by chem2016** [comment]
@ami-domadia @5t4mp5 @KristyHSC , could you look into the commit above, this includes Kristy's code and a cart component.

**Review by ghost — APPROVED** [review]
Please merge:) @chem2016

**Pull request merged**
